#pragma once
#include <Arduino.h>
#include <midi_Defs.h>

#ifndef DMIDIBLEUTIL_H
#define DMIDIBLEUTIL_H

// MIDI Channels
#define MIDI_CHANNEL_1  1
#define MIDI_CHANNEL_2  2
#define MIDI_CHANNEL_3  3
#define MIDI_CHANNEL_4  4
#define MIDI_CHANNEL_5  5
#define MIDI_CHANNEL_6  6
#define MIDI_CHANNEL_7  7
#define MIDI_CHANNEL_8  8
#define MIDI_CHANNEL_9  9
#define MIDI_CHANNEL_10 10
#define MIDI_CHANNEL_11 11
#define MIDI_CHANNEL_12 12
#define MIDI_CHANNEL_13 13
#define MIDI_CHANNEL_14 14
#define MIDI_CHANNEL_15 15
#define MIDI_CHANNEL_16 16

// MIDI Control Change (CC) Types - https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2
#define MIDI_CC_CONTROL_BANK_SELECT                      MidiControlChangeNumber.BankSelect
#define MIDI_CC_CONTROL_MODULATION_WHEEL                 MidiControlChangeNumber.ModulationWheel
#define MIDI_CC_CONTROL_BREATH_CONTROLLER                MidiControlChangeNumber.BreathController
#define MIDI_CC_CONTROL_FOOT_CONTROLLER                  MidiControlChangeNumber.FootController
#define MIDI_CC_CONTROL_PORTAMENTO_TIME                  MidiControlChangeNumber.PortamentoTime
#define MIDI_CC_CONTROL_DATA_ENTRY                       MidiControlChangeNumber.DataEntryMSB
#define MIDI_CC_CONTROL_VOLUME                           MidiControlChangeNumber.ChannelVolume
#define MIDI_CC_CONTROL_BALANCE                          MidiControlChangeNumber.Balance
#define MIDI_CC_CONTROL_PAN_POSITION                     MidiControlChangeNumber.Pan
#define MIDI_CC_CONTROL_EXPRESSION                       MidiControlChangeNumber.ExpressionController
#define MIDI_CC_CONTROL_EFFECT_CONTROL_1                 MidiControlChangeNumber.EffectControl1
#define MIDI_CC_CONTROL_EFFECT_CONTROL_2                 MidiControlChangeNumber.EffectControl2
#define MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_1     MidiControlChangeNumber.GeneralPurposeController1
#define MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_2     MidiControlChangeNumber.GeneralPurposeController2
#define MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_3     MidiControlChangeNumber.GeneralPurposeController3
#define MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_4     MidiControlChangeNumber.GeneralPurposeController4
#define MIDI_CC_CONTROL_DATA_ENTRY_LSB                   MidiControlChangeNumber.DataEntryLSB
#define MIDI_CC_CONTROL_SUSTAIN                          MidiControlChangeNumber.Sustain
#define MIDI_CC_CONTROL_PORTAMENTO_ON_OFF                MidiControlChangeNumber.Portamento
#define MIDI_CC_CONTROL_SOSTENUTO_ON_OFF                 MidiControlChangeNumber.Sostenuto
#define MIDI_CC_CONTROL_SOFT_PEDAL_ON_OFF                MidiControlChangeNumber.SoftPedal
#define MIDI_CC_CONTROL_LEGATO_FOOTSWITCH                MidiControlChangeNumber.Legato
#define MIDI_CC_CONTROL_HOLD                             MidiControlChangeNumber.Hold
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_1               MidiControlChangeNumber.SoundController1
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_2               MidiControlChangeNumber.SoundController2
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_3               MidiControlChangeNumber.SoundController3
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_4               MidiControlChangeNumber.SoundController4
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_5               MidiControlChangeNumber.SoundController5
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_6               MidiControlChangeNumber.SoundController6
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_7               MidiControlChangeNumber.SoundController7
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_8               MidiControlChangeNumber.SoundController8
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_9               MidiControlChangeNumber.SoundController9
#define MIDI_CC_CONTROL_SOUND_CONTROLLER_10              MidiControlChangeNumber.SoundController10
#define MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_5     MidiControlChangeNumber.GeneralPurposeController5
#define MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_6     MidiControlChangeNumber.GeneralPurposeController6
#define MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_7     MidiControlChangeNumber.GeneralPurposeController7
#define MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_8     MidiControlChangeNumber.GeneralPurposeController8
#define MIDI_CC_CONTROL_PORTAMENTO_CONTROL               MidiControlChangeNumber.PortamentoControl
#define MIDI_CC_CONTROL_EFFECT_1_DEPTH                   MidiControlChangeNumber.Effects1
#define MIDI_CC_CONTROL_EFFECT_2_DEPTH                   MidiControlChangeNumber.Effects2
#define MIDI_CC_CONTROL_EFFECT_3_DEPTH                   MidiControlChangeNumber.Effects3
#define MIDI_CC_CONTROL_EFFECT_4_DEPTH                   MidiControlChangeNumber.Effects4
#define MIDI_CC_CONTROL_EFFECT_5_DEPTH                   MidiControlChangeNumber.Effects5
#define MIDI_CC_CONTROL_DATA_INCREMENT                   MidiControlChangeNumber.DataIncrement
#define MIDI_CC_CONTROL_DATA_DECREMENT                   MidiControlChangeNumber.DataDecrement
#define MIDI_CC_CONTROL_NON_REGISTERED_PARAM_LSB         MidiControlChangeNumber.NRPNLSB
#define MIDI_CC_CONTROL_NON_REGISTERED_PARAM_MSB         MidiControlChangeNumber.NRPNMSB
#define MIDI_CC_CONTROL_REGISTERED_PARAM_LSB             MidiControlChangeNumber.RPNLSB
#define MIDI_CC_CONTROL_REGISTERED_PARAM_MSB             MidiControlChangeNumber.RPNMSB
#define MIDI_CC_CONTROL_CHANNEL_SOUND_OFF                MidiControlChangeNumber.AllSoundOff
#define MIDI_CC_CONTROL_CHANNEL_RESET_CONTROLLERS        MidiControlChangeNumber.ResetAllControllers
#define MIDI_CC_CONTROL_CHANNEL_LOCAL_CONTROL_ON_OFF     MidiControlChangeNumber.LocalControl
#define MIDI_CC_CONTROL_ALL_NOTES_OFF                    MidiControlChangeNumber.AllNotesOff
#define MIDI_CC_CONTROL_OMNI_MODE_OFF                    MidiControlChangeNumber.OmniModeOff
#define MIDI_CC_CONTROL_OMNI_MODE_ON                     MidiControlChangeNumber.OmniModeOn
#define MIDI_CC_CONTROL_MONO_MODE_ON                     MidiControlChangeNumber.MonoModeOn
#define MIDI_CC_CONTROL_POLY_MODE_ON                     MidiControlChangeNumber.PolyModeOn

// MIDI Control Change (CC) Numbers
#define MIDI_CC_CONTROL_0   MIDI_CC_CONTROL_BANK_SELECT
#define MIDI_CC_CONTROL_1   MIDI_CC_CONTROL_MODULATION_WHEEL
#define MIDI_CC_CONTROL_2   MIDI_CC_CONTROL_BREATH_CONTROLLER
#define MIDI_CC_CONTROL_4   MIDI_CC_CONTROL_FOOT_CONTROLLER
#define MIDI_CC_CONTROL_5   MIDI_CC_CONTROL_PORTAMENTO_TIME
#define MIDI_CC_CONTROL_6   MIDI_CC_CONTROL_DATA_ENTRY
#define MIDI_CC_CONTROL_7   MIDI_CC_CONTROL_VOLUME
#define MIDI_CC_CONTROL_8   MIDI_CC_CONTROL_BALANCE
#define MIDI_CC_CONTROL_10  MIDI_CC_CONTROL_PAN_POSITION
#define MIDI_CC_CONTROL_11  MIDI_CC_CONTROL_EXPRESSION
#define MIDI_CC_CONTROL_12  MIDI_CC_CONTROL_EFFECT_CONTROL_1
#define MIDI_CC_CONTROL_13  MIDI_CC_CONTROL_EFFECT_CONTROL_2
#define MIDI_CC_CONTROL_16  MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_1
#define MIDI_CC_CONTROL_17  MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_2
#define MIDI_CC_CONTROL_18  MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_3
#define MIDI_CC_CONTROL_19  MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_4
#define MIDI_CC_CONTROL_38  MIDI_CC_CONTROL_DATA_ENTRY_LSB
#define MIDI_CC_CONTROL_64  MIDI_CC_CONTROL_SUSTAIN
#define MIDI_CC_CONTROL_65  MIDI_CC_CONTROL_PORTAMENTO_ON_OFF
#define MIDI_CC_CONTROL_66  MIDI_CC_CONTROL_SOSTENUTO_ON_OFF
#define MIDI_CC_CONTROL_67  MIDI_CC_CONTROL_SOFT_PEDAL_ON_OFF
#define MIDI_CC_CONTROL_68  MIDI_CC_CONTROL_LEGATO_FOOTSWITCH
#define MIDI_CC_CONTROL_69  MIDI_CC_CONTROL_HOLD
#define MIDI_CC_CONTROL_70  MIDI_CC_CONTROL_SOUND_CONTROLLER_1
#define MIDI_CC_CONTROL_71  MIDI_CC_CONTROL_SOUND_CONTROLLER_2
#define MIDI_CC_CONTROL_72  MIDI_CC_CONTROL_SOUND_CONTROLLER_3
#define MIDI_CC_CONTROL_73  MIDI_CC_CONTROL_SOUND_CONTROLLER_4
#define MIDI_CC_CONTROL_74  MIDI_CC_CONTROL_SOUND_CONTROLLER_5
#define MIDI_CC_CONTROL_75  MIDI_CC_CONTROL_SOUND_CONTROLLER_6
#define MIDI_CC_CONTROL_76  MIDI_CC_CONTROL_SOUND_CONTROLLER_7
#define MIDI_CC_CONTROL_77  MIDI_CC_CONTROL_SOUND_CONTROLLER_8
#define MIDI_CC_CONTROL_78  MIDI_CC_CONTROL_SOUND_CONTROLLER_9
#define MIDI_CC_CONTROL_79  MIDI_CC_CONTROL_SOUND_CONTROLLER_10
#define MIDI_CC_CONTROL_80  MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_5
#define MIDI_CC_CONTROL_81  MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_6
#define MIDI_CC_CONTROL_82  MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_7
#define MIDI_CC_CONTROL_83  MIDI_CC_CONTROL_GENERAL_PURPOSE_CONTROLLER_8
#define MIDI_CC_CONTROL_84  MIDI_CC_CONTROL_PORTAMENTO_CONTROL
#define MIDI_CC_CONTROL_91  MIDI_CC_CONTROL_EFFECT_1_DEPTH
#define MIDI_CC_CONTROL_92  MIDI_CC_CONTROL_EFFECT_2_DEPTH
#define MIDI_CC_CONTROL_93  MIDI_CC_CONTROL_EFFECT_3_DEPTH
#define MIDI_CC_CONTROL_94  MIDI_CC_CONTROL_EFFECT_4_DEPTH
#define MIDI_CC_CONTROL_95  MIDI_CC_CONTROL_EFFECT_5_DEPTH
#define MIDI_CC_CONTROL_96  MIDI_CC_CONTROL_DATA_INCREMENT
#define MIDI_CC_CONTROL_97  MIDI_CC_CONTROL_DATA_DECREMENT
#define MIDI_CC_CONTROL_98  MIDI_CC_CONTROL_NON_REGISTERED_PARAM_LSB
#define MIDI_CC_CONTROL_99  MIDI_CC_CONTROL_NON_REGISTERED_PARAM_MSB
#define MIDI_CC_CONTROL_100 MIDI_CC_CONTROL_REGISTERED_PARAM_LSB
#define MIDI_CC_CONTROL_101 MIDI_CC_CONTROL_REGISTERED_PARAM_MSB
#define MIDI_CC_CONTROL_120 MIDI_CC_CONTROL_CHANNEL_SOUND_OFF
#define MIDI_CC_CONTROL_121 MIDI_CC_CONTROL_CHANNEL_RESET_CONTROLLERS
#define MIDI_CC_CONTROL_122 MIDI_CC_CONTROL_CHANNEL_LOCAL_CONTROL_ON_OFF
#define MIDI_CC_CONTROL_123 MIDI_CC_CONTROL_ALL_NOTES_OFF
#define MIDI_CC_CONTROL_124 MIDI_CC_CONTROL_OMNI_MODE_OFF
#define MIDI_CC_CONTROL_125 MIDI_CC_CONTROL_OMNI_MODE_ON
#define MIDI_CC_CONTROL_126 MIDI_CC_CONTROL_MONO_MODE_ON
#define MIDI_CC_CONTROL_127 MIDI_CC_CONTROL_POLY_MODE_ON

// MIDI Notes
#define MIDI_NOTE_A0    21
#define MIDI_NOTE_Bb0   22
#define MIDI_NOTE_B0    23
#define MIDI_NOTE_C1    24
#define MIDI_NOTE_Db1   25
#define MIDI_NOTE_D1    26
#define MIDI_NOTE_Eb1   27
#define MIDI_NOTE_E1    28
#define MIDI_NOTE_F1    29
#define MIDI_NOTE_Gb1   30
#define MIDI_NOTE_G1    31
#define MIDI_NOTE_Ab1   32
#define MIDI_NOTE_A1    33
#define MIDI_NOTE_Bb1   34
#define MIDI_NOTE_B1    35
#define MIDI_NOTE_C2    36
#define MIDI_NOTE_Db2   37
#define MIDI_NOTE_D2    38
#define MIDI_NOTE_Eb2   39
#define MIDI_NOTE_E2    40
#define MIDI_NOTE_F2    41
#define MIDI_NOTE_Gb2   42
#define MIDI_NOTE_G2    43
#define MIDI_NOTE_Ab2   44
#define MIDI_NOTE_A2    45
#define MIDI_NOTE_Bb2   46
#define MIDI_NOTE_B2    47
#define MIDI_NOTE_C3    48
#define MIDI_NOTE_Db3   49
#define MIDI_NOTE_D3    50
#define MIDI_NOTE_Eb3   51
#define MIDI_NOTE_E3    52
#define MIDI_NOTE_F3    53
#define MIDI_NOTE_Gb3   54
#define MIDI_NOTE_G3    55
#define MIDI_NOTE_Ab3   56
#define MIDI_NOTE_A3    57
#define MIDI_NOTE_Bb3   58
#define MIDI_NOTE_B3    59
#define MIDI_NOTE_C4    60
#define MIDI_NOTE_Db4   61
#define MIDI_NOTE_D4    62
#define MIDI_NOTE_Eb4   63
#define MIDI_NOTE_E4    64
#define MIDI_NOTE_F4    65
#define MIDI_NOTE_Gb4   66
#define MIDI_NOTE_G4    67
#define MIDI_NOTE_Ab4   68
#define MIDI_NOTE_A4    69
#define MIDI_NOTE_Bb4   70
#define MIDI_NOTE_B4    71
#define MIDI_NOTE_C5    72
#define MIDI_NOTE_Db5   73
#define MIDI_NOTE_D5    74
#define MIDI_NOTE_Eb5   75
#define MIDI_NOTE_E5    76
#define MIDI_NOTE_F5    77
#define MIDI_NOTE_Gb5   78
#define MIDI_NOTE_G5    79
#define MIDI_NOTE_Ab5   80
#define MIDI_NOTE_A5    81
#define MIDI_NOTE_Bb5   82
#define MIDI_NOTE_B5    83
#define MIDI_NOTE_C6    84
#define MIDI_NOTE_Db6   85
#define MIDI_NOTE_D6    86
#define MIDI_NOTE_Eb6   87
#define MIDI_NOTE_E6    88
#define MIDI_NOTE_F6    89
#define MIDI_NOTE_Gb6   90
#define MIDI_NOTE_G6    91
#define MIDI_NOTE_Ab6   92
#define MIDI_NOTE_A6    93
#define MIDI_NOTE_Bb6   94
#define MIDI_NOTE_B6    95
#define MIDI_NOTE_C7    96
#define MIDI_NOTE_Db7   97
#define MIDI_NOTE_D7    98
#define MIDI_NOTE_Eb7   99
#define MIDI_NOTE_E7    100
#define MIDI_NOTE_F7    101
#define MIDI_NOTE_Gb7   102
#define MIDI_NOTE_G7    103
#define MIDI_NOTE_Ab7   104
#define MIDI_NOTE_A7    105
#define MIDI_NOTE_Bb7   106
#define MIDI_NOTE_B7    107
#define MIDI_NOTE_C8    108
#define MIDI_NOTE_Db8   109
#define MIDI_NOTE_D8    110
#define MIDI_NOTE_Eb8   111
#define MIDI_NOTE_E8    112
#define MIDI_NOTE_F8    113
#define MIDI_NOTE_Gb8   114
#define MIDI_NOTE_G8    115
#define MIDI_NOTE_Ab8   116
#define MIDI_NOTE_A8    117
#define MIDI_NOTE_Bb8   118
#define MIDI_NOTE_B8    119
#define MIDI_NOTE_C9    120
#define MIDI_NOTE_Db9   121
#define MIDI_NOTE_D9    122
#define MIDI_NOTE_Eb9   123
#define MIDI_NOTE_E9    124
#define MIDI_NOTE_F9    125
#define MIDI_NOTE_Gb9   126
#define MIDI_NOTE_G9    127

#endif
